### ISSUE TITLE
Concept

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/python-binding#1]
- The binding does not reproduce a hierarchical structure anywhere.
- We only store in the Python process the objects that we resolve or that we create.
- The Python object that represents a Corto object is not a proxy for something; e.g. when we do "a.x", "x" was already a member of this Python object, it is not necessary to access a store for a member call.
- The first thing that we want to implement is roughly:
    - corto_resolve
    - corto_instanceof
    - corto_typeof
    - corto_nameof

- The tentative overall architecture for this would be a corto [C] component that consumes the Python C API (https://docs.python.org/3.5/c-api/intro.html).

**Comment by SanderMertens** [comment]
A good tutorial on how to write Python extensions in C:
http://www.tutorialspoint.com/python/python_further_extensions.htm

**Comment by jleeothon** [comment]
I will close this issue since the project has gotten started already, being a bit more than 1000 lines now.
