### ISSUE TITLE
LD_LIBRARY_PATH not always available

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/python-binding#5]
In Linux, Python cannot always find libcorto.so. The path to it needs to be set in LD_LIBRARY_PATH.

Some ideas when to set it:

## When the module is loaded.

Doesn't work, since the module is the library itself.

## In .bashrc or .bash_profile or a similar file

Needs to figure out the current corto version. Could be done with `corto -v` which right now outputs e.g. `0.2.11-alpha`.

When would it be appended? During installation of the package, I guess. Need to read documentation for  distutils. To see how that works.

**Comment by SanderMertens** [comment]
If you can, try to solve it the same way the Corto build system does. `LD_LIBRARY_PATH` isn't a very nice solution.

The Corto build system doesn't use -l to link with a library. Instead it provides the full path to the library to the compiler. This way, at runtime, the generated executable (or shared object) will always know where to find the library, as long as it is in the same location.

Traditional way of linking a library:
```
gcc foo.c -Lsome/library/path -lcorto ...
```
What the corto build system does:
```
gcc foo.c some/library/path/libcorto.so
```

**Comment by jleeothon** [comment]
Appears to be solvable by the `runtime_library_dirs` to `Extension` in setup.py.

**Comment by jleeothon** [comment]
Verified on Mac as of today.
